<?php

declare(strict_types=1);

use OffloadProject\Mandate\Services\MandateManager;
use OffloadProject\Mandate\Services\TypescriptGenerator;

beforeEach(function () {
    app(MandateManager::class)->clearCache();
});

test('it generates typescript with permissions', function () {
    $generator = app(TypescriptGenerator::class);
    $output = $generator->generate();

    expect($output)->toContain('export const UserPermissions = {');
    expect($output)->toContain('VIEW: "view users"');
    expect($output)->toContain('CREATE: "create users"');
    expect($output)->toContain('UPDATE: "update users"');
    expect($output)->toContain('DELETE: "delete users"');
    expect($output)->toContain('EXPORT: "export users"');
    expect($output)->toContain('} as const;');
});

test('it generates typescript with roles', function () {
    $generator = app(TypescriptGenerator::class);
    $output = $generator->generate();

    expect($output)->toContain('export const SystemRoles = {');
    expect($output)->toContain('ADMIN: "admin"');
    expect($output)->toContain('EDITOR: "editor"');
    expect($output)->toContain('VIEWER: "viewer"');
    expect($output)->toContain('} as const;');
});

test('it generates typescript with features', function () {
    $generator = app(TypescriptGenerator::class);
    $output = $generator->generate();

    expect($output)->toContain('export const Features = {');
    expect($output)->toContain('ExportFeature: "export"');
    expect($output)->toContain('} as const;');
});

test('it includes auto-generated header comment', function () {
    $generator = app(TypescriptGenerator::class);
    $output = $generator->generate();

    expect($output)->toStartWith('// This file is auto-generated by mandate:typescript. Do not edit manually.');
});

test('it escapes special characters in permission values', function () {
    // This test verifies the escaping logic works
    $generator = app(TypescriptGenerator::class);
    $output = $generator->generate();

    // The output should be valid TypeScript (no unescaped quotes)
    expect($output)->not->toContain('""'); // No empty strings from bad escaping
});

test('it generates valid typescript syntax', function () {
    $generator = app(TypescriptGenerator::class);
    $output = $generator->generate();

    // Count opening and closing braces should match
    $openBraces = mb_substr_count($output, '{');
    $closeBraces = mb_substr_count($output, '}');

    expect($openBraces)->toBe($closeBraces);

    // Each export should end with "as const;"
    $exports = mb_substr_count($output, 'export const');
    $asConst = mb_substr_count($output, '} as const;');

    expect($exports)->toBe($asConst);
});
