name: Change Champion

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]
  push:
    branches: [ main ]
    paths:
      - '.changes/*.md'
      - '!.changes/README.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  change-champion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: 'Change Champion'
          check-regexp: 'PHP.*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - uses: offload-project/change-champion@v1.9.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
